const canvas = document.getElementById('arena');
const ctx = canvas.getContext('2d');
const W = canvas.width, H = canvas.height;
const keys = new Set();
let mode = 'solo';
let level = 1;
let running = false;
let lastTime = 0;
let player, enemy;

const ui = { start: document.getElementById('startScreen'), level: document.getElementById('levelScreen'), over: document.getElementById('gameOverScreen'), playerHealth: document.getElementById('playerHealth'), enemyHealth: document.getElementById('enemyHealth'), playerHealthText: document.getElementById('playerHealthText'), enemyHealthText: document.getElementById('enemyHealthText'), playerStreak: document.getElementById('playerStreak'), enemyStatus: document.getElementById('enemyStatus'), levelText: document.getElementById('levelText'), modeText: document.getElementById('modeText'), resultKicker: document.getElementById('resultKicker'), resultTitle: document.getElementById('resultTitle'), resultDetail: document.getElementById('resultDetail'), gameOverDetail: document.getElementById('gameOverDetail') };
const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
const show = element => element.classList.add('visible');
const hide = element => element.classList.remove('visible');

class Fighter {
  constructor(x, side, name, color) { this.x = x; this.y = 560; this.vy = 0; this.side = side; this.name = name; this.color = color; this.hp = 100; this.attack = 0; this.cooldown = 0; this.hitFlash = 0; this.streak = 0; }
  jump() { if (this.y >= 559) this.vy = -620; }
  punch() { if (this.cooldown <= 0) { this.attack = .22; this.cooldown = .52; } }
  update(dt) { this.y += this.vy * dt; this.vy += 1500 * dt; if (this.y > 560) { this.y = 560; this.vy = 0; } this.attack = Math.max(0, this.attack - dt); this.cooldown = Math.max(0, this.cooldown - dt); this.hitFlash = Math.max(0, this.hitFlash - dt); }
}
function startGame(newMode = 'solo') { mode = newMode; level = 1; running = true; hide(ui.start); hide(ui.level); hide(ui.over); resetRound(); }
function resetRound() { player = new Fighter(390, 1, 'KAGE', '#79b6b3'); enemy = new Fighter(890, -1, mode === 'solo' ? 'AKUMA' : 'RONIN', '#e1483e'); enemy.hp = 82 + level * 1.8; updateHud(); }
function updateHud() { ui.playerHealth.style.width = `${player.hp}%`; ui.enemyHealth.style.width = `${(enemy.hp / (82 + level * 1.8)) * 100}%`; ui.playerHealthText.textContent = `${Math.ceil(player.hp)} HP`; ui.enemyHealthText.textContent = `${Math.ceil(enemy.hp)} HP`; ui.playerStreak.textContent = `STREAK ${player.streak}`; ui.enemyStatus.textContent = level > 6 ? 'THREAT HIGH' : level > 3 ? 'THREAT MID' : 'THREAT LOW'; ui.levelText.textContent = `LEVEL ${String(level).padStart(2, '0')}`; ui.modeText.textContent = mode === 'solo' ? 'SOLO // VS AI' : 'DUEL // TWO PLAYER'; }
function hitTest(attacker, defender) { const distance = Math.abs(attacker.x - defender.x); return attacker.attack > .08 && attacker.attack < .18 && distance < 142 && Math.abs(attacker.y - defender.y) < 75; }
function combat(dt) { const playerPunch = keys.has('Space'); const jumpKey = keys.has('Enter'); if (playerPunch) player.punch(); if (jumpKey) player.jump(); if (mode === 'two') { if (keys.has('AltLeft') || keys.has('AltRight')) enemy.punch(); if (keys.has('ControlLeft') || keys.has('ControlRight')) enemy.jump(); const distance = Math.abs(player.x - enemy.x); if (distance > 118) { const step = 35 * dt; player.x += step; enemy.x -= step; } } else { const distance = Math.abs(player.x - enemy.x); if (distance > 115) enemy.x += Math.sign(player.x - enemy.x) * (80 + level * 5) * dt; if (distance < 145 && enemy.cooldown <= 0 && Math.random() < dt * (0.6 + level * .1)) enemy.punch(); if (enemy.y >= 559 && Math.random() < dt * .12) enemy.jump(); }
  if (hitTest(player, enemy) && !enemy.hitFlash) { enemy.hp -= 9; enemy.hitFlash = .18; player.streak++; } if (hitTest(enemy, player) && !player.hitFlash) { player.hp -= mode === 'solo' ? 5 + level * .35 : 8; player.hitFlash = .18; player.streak = 0; } if (player.hp <= 0) lose(); else if (enemy.hp <= 0) win(); updateHud(); }
function win() { running = false; ui.resultKicker.textContent = level === 10 ? 'THE FRONTIER IS YOURS' : 'LEVEL CLEARED'; ui.resultTitle.textContent = level === 10 ? 'SHADOWFALL' : `LEVEL ${String(level).padStart(2, '0')}`; ui.resultDetail.textContent = level === 10 ? 'The red tie falls. The last gate is open.' : `The next shadow hits harder. Level ${level + 1} is waiting.`; show(ui.level); }
function lose() { running = false; ui.gameOverDetail.textContent = `Level ${String(level).padStart(2, '0')} held the line. Learn its rhythm and strike again.`; show(ui.over); }
function drawBackground(t) { const sky = ctx.createLinearGradient(0, 0, 0, H); sky.addColorStop(0, '#101e27'); sky.addColorStop(.52, '#273936'); sky.addColorStop(1, '#111917'); ctx.fillStyle = sky; ctx.fillRect(0, 0, W, H); ctx.fillStyle = '#d4bd79'; ctx.globalAlpha = .6; ctx.beginPath(); ctx.arc(1030, 138, 64, 0, Math.PI * 2); ctx.fill(); ctx.globalAlpha = 1; for (let i = 0; i < 13; i++) { const x = i * 109 + ((i * 41) % 50); const lean = Math.sin(i * 2.1) * 20; ctx.strokeStyle = i % 2 ? '#18352f' : '#1e4035'; ctx.lineWidth = 17; ctx.beginPath(); ctx.moveTo(x, 570); ctx.lineTo(x + lean, 80 + (i % 3) * 45); ctx.stroke(); ctx.lineWidth = 4; ctx.strokeStyle = '#45634e'; for (let j = 0; j < 5; j++) { const y = 180 + j * 78 + (i % 2) * 13; ctx.beginPath(); ctx.moveTo(x - 9, y); ctx.lineTo(x + lean + 9, y); ctx.stroke(); } ctx.fillStyle = '#426348'; for (let j = 0; j < 4; j++) { const y = 150 + j * 93; ctx.beginPath(); ctx.ellipse(x + lean - 23, y, 39, 10, -.5, 0, Math.PI * 2); ctx.fill(); ctx.beginPath(); ctx.ellipse(x + lean + 25, y + 31, 35, 9, .5, 0, Math.PI * 2); ctx.fill(); } }
  ctx.fillStyle = '#0d1718'; ctx.fillRect(0, 580, W, 140); ctx.strokeStyle = '#aa794e'; ctx.lineWidth = 5; ctx.beginPath(); ctx.moveTo(0, 598); ctx.lineTo(W, 598); ctx.stroke(); ctx.strokeStyle = '#543b2e'; ctx.lineWidth = 2; for (let i = 0; i < 18; i++) { ctx.beginPath(); ctx.moveTo(i * 80, 600); ctx.lineTo(i * 80 + 30, 720); ctx.stroke(); } ctx.fillStyle = '#152724'; ctx.fillRect(0, 606, W, 114); ctx.fillStyle = '#213d35'; ctx.globalAlpha = .7; for (let i = 0; i < 34; i++) { ctx.beginPath(); ctx.arc((i * 89 + t * 10) % W, 625 + (i * 17) % 90, 2, 0, Math.PI * 2); ctx.fill(); } ctx.globalAlpha = 1; }
function drawFighter(f) { const x = f.x, y = f.y; ctx.save(); ctx.translate(x, y); ctx.scale(f.side, 1); ctx.globalAlpha = f.hitFlash ? .5 : 1; ctx.fillStyle = '#040607'; ctx.beginPath(); ctx.ellipse(0, 13, 48, 10, 0, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#101518'; ctx.fillRect(-22, -123, 44, 79); ctx.beginPath(); ctx.arc(0, -145, 25, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = f.color; ctx.fillRect(-24, -102, 48, 11); ctx.beginPath(); ctx.moveTo(-26, -95); ctx.lineTo(24, -88); ctx.lineTo(78, -113); ctx.lineWidth = 8; ctx.strokeStyle = f.color; ctx.stroke(); ctx.strokeStyle = '#11191a'; ctx.lineWidth = 12; ctx.beginPath(); ctx.moveTo(-14, -45); ctx.lineTo(-32, 5); ctx.moveTo(14, -45); ctx.lineTo(36, 5); ctx.stroke(); ctx.strokeStyle = '#20292b'; ctx.lineWidth = 11; ctx.beginPath(); ctx.moveTo(-13, -114); ctx.lineTo(-48, f.attack ? -108 : -83); ctx.stroke(); ctx.fillStyle = f.color; ctx.fillRect(-57, f.attack ? -114 : -89, 17, 13); if (f.attack) { ctx.strokeStyle = f.color; ctx.globalAlpha = .4; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(62, -102, 35, -.6, .3); ctx.stroke(); } ctx.restore(); }
function draw(t) { drawBackground(t); drawFighter(player); drawFighter(enemy); if (!running) { ctx.fillStyle = '#d6ae6233'; ctx.fillRect(0, 0, W, H); } }
function loop(time) { const dt = Math.min(.033, (time - lastTime) / 1000 || 0); lastTime = time; if (running) { player.update(dt); enemy.update(dt); combat(dt); } draw(time / 1000); requestAnimationFrame(loop); }
window.addEventListener('keydown', event => { keys.add(event.code); if (['Space', 'Enter', 'AltLeft', 'AltRight', 'ControlLeft', 'ControlRight'].includes(event.code)) event.preventDefault(); }); window.addEventListener('keyup', event => keys.delete(event.code));
document.getElementById('soloButton').addEventListener('click', () => startGame('solo')); document.getElementById('twoPlayerButton').addEventListener('click', () => startGame('two')); document.getElementById('continueButton').addEventListener('click', () => { if (level >= 10) { startGame('solo'); return; } level++; hide(ui.level); resetRound(); running = true; }); document.getElementById('retryButton').addEventListener('click', () => { hide(ui.over); resetRound(); running = true; });
resetRound();
requestAnimationFrame(loop);
